version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    command: npm run dev
    container_name: nodejs
    restart: unless-stopped
    networks:
      - app-network
  webserver:
    image: nginx:latest
    container_name: webserver
    restart: unless-stopped
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - web-root:/var/www/html
    depends_on:
    - nodejs
    networks:
    - app-network



networks:
  app-network:
    driver: bridge

