version: '3'

services:
  nodejs:
    build: .
    image: nodejs
    command: npm run dev
    volumes:
      - .:/home/nodejs/app
      - /home/nodejs/app/node_modules
    container_name: nodejs
    restart: unless-stopped
    ports:
        # Service will be accessible on the host at port 8080.
        - "80:${PORT:-8080}"
        - "3000:${PORT:-3000}"
    environment:
        # /run/docs/reference/container-contract
        PORT: ${PORT:-3000}
        WSPORT: ${PORT:-3000}
        DB: mongodb://mongo:27017/db
        SALT_SECRET: 312iu4212hui
    depends_on: 
      - mongo
    networks:
      - app-network
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - app-network


networks:
  app-network:
    driver: bridge
