version: '3'

services:
  nodejs:
    build: .
    image: nodejs
    command: npm run dev
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
    container_name: nodejs
    restart: unless-stopped
    ports:
        # Service will be accessible on the host at port 9090.
        - "80:${PORT:-8080}"
    environment:
        # /run/docs/reference/container-contract
        PORT: ${PORT:-8080}
    networks:
      - app-network


networks:
  app-network:
    driver: bridge
